sudo: false
language: node_js
node_js:
  - "14"
  - "12"
  - "10"
  - "8"
script:
  - npm run lint
  - npm run prettier-ci
  - npm test
after_script:
  - if [ $(echo "${TRAVIS_NODE_VERSION}" | cut -d'.' -f1) -ge 6 ]; then
    npm run coveralls;
    fi

git:
  depth: 10
os:
  - linux
  - osx
